config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  root "sessions#new"
  resources :users
  resources :favorites,only:[:index,:create,:destroy]
  resources :sessions, only:[:new, :create, :destroy]
  resources :relationships, only:[:create, :destroy]
  resources :pictures do
    collection do
      post :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/inbox" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :content,length:{maximum:500}
  validates :image, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255}, format:{with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password_digest, presence:true, length:{minimum:6}

  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites_pictures, through: :favorites, source: :picture
  has_many :active_relationships, foreign_key: 'follower_id', class_name:'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name:'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  after_initialize :set_defalt_avatar

  def set_defalt_avatar
    self.avatar = File.open("./app/assets/images/f_f_event_75_s128_f_event_75_1bg.png") if avatar.blank?
  end

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_pictures = current_user.favorites_pictures.all
  end

  def create
    current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to picture_path(params[:picture_id])
  end

  def destroy
    picture_number = Favorite.find(params[:id]).picture_id
    @my_favorite = current_user.favorites.find_by(params[:picture_id])
    @my_favorite.destroy
    redirect_to picture_path(picture_number)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture,only:[:show,:edit,:update,:destroy]
  def index
    @pictures = Picture.all.order(created_at: :desc)
  end

  def new
    @picture = current_user.pictures.new
  end

  def create
    @picture = current_user.pictures.new(picture_params)
    if params[:back]
      @file_name = @picture.image.filename
      render :new
    else
      if @picture.save
        #本番環境でメール投稿を実装する際のコード
        # ConfirmMailer.confirm_mail(@picture).deliver
        redirect_to pictures_path, notice:"投稿しました"
      else
        render :new
      end
    end
  end

  def show
    current_user
    @favorite = current_user.favorites.find_by(picture_id: params[:id])
    @count_favorites = Favorite.where(picture_id: params[:id]).count
  end

  def edit
    redirect_to users_path if current_user.id != @picture.user.id
  end

  def update
    redirect_to users_path if current_user.id != @picture.user.id
    if @picture.update(picture_params)
      redirect_to picture_path(@picture.id), notice:"投稿を更新しました"
    else
      render :edit
    end
  end

  def destroy
    redirect_to users_path if current_user.id != @picture.user.id
    if @picture.destroy
      redirect_to pictures_path, notice:"投稿を削除しました"
    else
      render :show
    end
  end

  def confirm
    @picture = current_user.pictures.new(picture_params)
    @file_name = @picture.image.filename
    render :new if @picture.invalid?
  end

  private
  def picture_params
    params.require(:picture).permit(:content,:image,:image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  respond_to? :js

  def create
    if loged_in?
      @user = User.find(params[:relationship][:followed_id])
      current_user.follow!(@user)
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id]= user.id
      redirect_to users_path,notice:"ログインしました"
    else
      flash.now[:notice] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only:[:show,:edit,:update,:destroy]
  def index
    if loged_in?
      @users = User.all
    else
      redirect_to new_session_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, notice:"アカウントを作成しました"
    else
      render :new
    end
  end

  def show
    current_user
    @pictures = @user.pictures.all.order(created_at: :desc)
  end

  def edit
    redirect_to users_path if current_user.id != @user.id
  end

  def update
    if current_user.id == @user.id
      if @user.update(user_params)
        redirect_to user_path(@user.id), notice:"ユーザー情報を変更しました"
      else
        render :edit
      end
    else
      redirect_to users_path
    end
  end

   private
   def user_params
     params.require(:user).permit(:name, :email, :password,:password_confirmation,:avatar,:avatar_cache,:greeting )
   end

   def set_user
     @user = User.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "create" || action_name == "confirm"
      confirm_pictures_path
    elsif action_name == "edit"
      picture_path(@picture.id)
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def loged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<div class="main">
  <h6><%= current_user.name %>さんがいいねした写真一覧</h6>
  <div class="card-container">
    <% @favorite_pictures.each do |picture| %>
      <%= link_to picture_path(picture.id), class:"card-item" do %>
        <%= image_tag(picture.image.url,class:"square-image") if picture.image && picture.image.url %>
        <div class="card-img-overlay disappear">
          <div class="like-status">
            <table>
              <tbody>
                <tr>
                  <td class="align-middle">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ffffff" class="bi bi-heart-fill" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                    </svg>
                  <%= picture.favorites.count %>
                  </td>
                </tr>
              </tbody>
           </table>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareSnaps</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="sticky-top">
      <div class="container-fluid card-body">
        <div class="row justify-content-between">
          <div class="col-6">
            <h2 class="font-weight-bold">SHARE SNAPS</h2>
          </div>
          <div class="col-6 d-flex justify-content-end">
          <% if loged_in? %>
            <%= link_to image_tag('home-outline.svg',class:"svg-icon", style:"width:25px;"), users_path ,class:"p-2" %>
            <%= link_to image_tag('compass-outline.svg',class:"svg-icon"), pictures_path ,class:"p-2"%>
            <%= link_to image_tag('heart-outline.svg',class:"svg-icon"),favorites_path,class:"p-2" %>
            <%= link_to image_tag('add-circle-outline.svg',class:"svg-icon"), new_picture_path ,class:"p-2" %>
            <%= link_to user_path(@current_user.id) ,class:"p-2" do %>
              <% if @current_user.avatar.url %>
                <%= image_tag @current_user.avatar.url,class:"avatar-sm" %>
              <% else %>
                <%= image_tag 'f_f_event_75_s128_f_event_75_1bg.png',class:"avatar-sm" %>
              <% end %>
            <% end %>
            <%= link_to "LOGOUT", session_path(@current_user.id), {method: :delete, class:"ml-2 p-2 btn btn-outline-dark btn-sm" } %>
          <% else %>
            <%= link_to "SignUp", new_user_path  ,class:"p-2 btn btn-outline-dark btn-sm" %>
            <%= link_to "Login", new_session_path ,class:"p-2 ml-2 btn btn-outline-dark btn-sm" %>
            <% end %>
          </div>
        </div>
      </div>
    </header>
    <% if notice %>
      <div class="alert alert-info"><%= notice %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<h2 class="text-center">New Posts</h2>
<div class="card card-center" style="max-width:500px;">
  <div class="card-body">
    <%= form_with(model: @picture, local: true, url: choose_new_or_edit ,class:"needs-validation") do |f| %>
      <% if @picture.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <% @picture.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        </div>
      <% end %>
      <div class="mb-3">
        <%= f.label :content, class:"form-label" %>
        <%= f.text_field :content, class:"form-control form-control-sm" %>
      </div>
      <div class="mb-3">
        <%= f.label :image, class:"form-label"%>
        <div class="custom-file">
          <%= f.file_field :image, class:"custom-file-input",id:"inputFile01",required:"required" %>
          <label class="custom-file-label" id="selectedFiles" for="inputFile01" data-browse="参照">
            <% if @file_name %>
              <%= @file_name %>
            <% else %>
              ファイルを選択...
            <% end %>
          </label>
        </div>
        <div class="invalid-feedback">画像ファイルを選択してください</div>
      </div>
      <div class="text-center">
        <%= f.submit "送信", class:"btn btn-outline-dark btn-sm submit" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pictures/confirm.html.erb
<div class="card card-center" style="max-width:500px;">
  <div class="card-body">
    <%= form_with(model: @picture, local: true) do |f| %>
      <%= f.hidden_field :content %>
      <%= f.hidden_field :image_cache %>
      <div class="mb-3">
        <%= f.label :content ,class:"form-label"%>
        <div>
          <%= @picture.content %>
        </div>
      </div>
      <div class="mb-3">
        <%= f.label :image %>
        <div>
          <%= image_tag(@picture.image.url ,class:"confirm-pic") %>
        </div>
      </div>
      <div class="text-center">
        <%= f.submit "送信" , class:"btn btn-outline-dark btn-sm" %>
        <%= f.submit "戻る", name:"back" , class:"btn btn-outline-dark btn-sm" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pictures/edit.html.erb
<%= render 'form' %>
<div class="text-center">
  <%= link_to "戻る", picture_path(@picture.id) , class:"btn btn-outline-dark btn-sm" %>
</div>

app/views/pictures/index.html.erb
<div class="main">
  <div class="card-container">
    <% @pictures.each do |picture| %>
      <%= link_to picture_path(picture.id), class:"card-item" do %>
        <%= image_tag(picture.image.url,class:"square-image") if picture.image && picture.image.url %>
        <div class="card-img-overlay disappear">
          <div class="like-status">
            <table>
              <tbody>
                <tr>
                  <td class="align-middle">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ffffff" class="bi bi-heart-fill" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                    </svg>
                  <%= picture.favorites.count %>
                  </td>
                </tr>
              </tbody>
           </table>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pictures/new.html.erb
<%= render 'form' %>

app/views/pictures/show.html.erb
<div class="container-fluid card card-center rounded-0">
  <div class="row">
    <div class="col-8 bg-dark p-0" style="text-align:center;">
      <%= image_tag @picture.image.url%>
    </div>
    <div class="col-4 border-left card p-0 border-top-0 border-right-0 border-bottom-0 rounded-0 picture-content">
      <div class="card-header">
        <% if @picture.user.avatar.url %>
          <%= link_to user_path(@picture.user.id) do %>
          <%= image_tag @picture.user.avatar.url, class:"avatar-sm"%>
          <% end %>
        <% else %>
          <%= link_to user_path(@picture.user.id) do %>
          <img class="avatar-sm">
          <% end %>
        <% end %>
        <%= @picture.user.name %>
      </div>
      <div class="card-body border-bottom" style="max-height:300px;">
        <p class="posted-time"><%= @picture.created_at.strftime('%Y/%m/%d %H:%M') %></p>
        <p class="text-wrap"><%= @picture.content %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <% if @favorite.present? %>
            <%= link_to favorite_path(id: @favorite.id), method: :delete, class:"like" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ff0000" class="bi bi-heart-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
              </svg>
            <% end %>
          <% else %>
            <%= link_to favorites_path(picture_id: @picture.id), method: :post ,class:"dis-like" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ff0000" class="bi bi-heart" viewBox="0 0 16 16">
                <path d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
              </svg>
            <% end %>
          <% end %>
          <%= @count_favorites %>
        </li>
        <li class="text-center p-2">
          <% if @current_user.id == @picture.user.id %>
          <span>
          <%= link_to "編集", edit_picture_path(@picture.id) ,class:"btn btn-outline-dark btn-sm" %>
          </span>
          <span>
          <%= link_to("削除", picture_path(@picture.id), method: :delete, data:{confirm:"本当に削除してよろしいですか？"}, class:"btn btn-outline-dark btn-sm") %>
          </span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/relationships/create.js.erb
$("#follow_form_"+"<%= @user.id %>").html("<%= escape_javascript(render partial: 'users/follow_form', locals: { user: @user } ) %>")

app/views/relationships/destroy.js.erb
$("#follow_form_"+"<%= @user.id %>").html("<%= escape_javascript( render partial: 'users/follow_form', locals: { user: @user } ) %>")

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id))  do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "フォロー解除" %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="card-center" style="width:150px; height:150px;">
  <% if @user.avatar.url %>
   <%= image_tag(@user.avatar.url, class:"avatar-lg") %>
  <% else %>
   <img class="avatar-lg">
  <% end %>
</div>
<div class="card card-center" style="max-width:500px;">
  <div class="card-body">
    <%= form_with(model: @user, local: true) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <% @user.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        </div>
      <% end %>
      <div class="mb-3">
        <%= f.label :name, class:"form-label" %>
        <%= f.text_field :name, class:"form-control form-control-sm" %>
      </div>
      <div class="mb-3">
        <%= f.label :email, class:"form-label"  %>
        <%= f.text_field :email, class:"form-control form-control-sm" %>
      </div>
      <div class="mb-3">
        <%= f.label :"プロフィール画像", class:"form-label"%>
        <div class="custom-file">
          <%= f.file_field :avatar, class:"custom-file-input" %>
          <label class="custom-file-label" data-browse="参照">ファイルを選択...</label>
        </div>
      </div>
      <div class="mb-3">
        <%= f.label :greeting, class:"form-label"  %>
        <%= f.text_field :greeting, class:"form-control form-control-sm" %>
      </div>
      <div class="mb-3">
        <%= f.label :password, class:"form-label" %>
        <%= f.password_field :password, class:"form-control form-control-sm" %>
      </div>
      <div class="text-center">
        <%= f.submit "変更", class:"btn btn-outline-dark btn-sm"  %>
      </div>
    <% end %>
  </div>
</div>

<!-- #前
<div class="form-group mb-3">
  <label class="control-rabel" for="picture_image">Image</label>
  <input type="filestyle" data-buttontext="ファイル選択" type="file" name="picture[image]",id="picture_image">
</div>

#後 -->

app/views/users/index.html.erb
<div class="card card-center" style="max-width:500px;">
  <% @users.each do |user| %>
    <div class="card-body container">
      <div class="row">
        <div class="col-4">
          <% if user.avatar.url.nil? %>
           <%= link_to image_tag('f_f_event_75_s128_f_event_75_1bg.png',class:"avatar-md"),user_path(user.id) %>
          <% else %>
            <%= link_to image_tag(user.avatar.url, class:"avatar-md"),user_path(user.id) %>
          <% end %>
        </div>
        <div class="col-8">
          <div class="mb-2">
            <h5><%= user.name %><h5>
          </div>
          <div class="mb-2">
            <p><%= user.greeting %></p>
          </div>
          <div class="mb-2">
            <%= render 'follow_form', user: user %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h2 class="text-center">Sign up</h2>
<div class="card card-center" style="max-width:500px;">
  <div class="card-body">
    <%= form_with(model: @user, local: true, class:"needs-validation",novalidate:"novalidate") do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <% @user.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        </div>
      <% end %>
      <div class="mb-3">
        <%= f.label :name , class:"form-label",for:"validationCustom01" %>
        <%= f.text_field :name, class:"form-control form-control-sm",id:"validationCustom01",required:"required" %>
        <div class="invalid-feedback">入力してください</div>
      </div>
      <div class="mb3">
        <%= f.label :email, class:"form-label",for:"validationCustom02" %>
        <%= f.text_field :email, class:"form-control form-control-sm",id:"validationCustom02",required:"required" %>
        <div class="invalid-feedback">入力してください</div>
      </div>
      <div class="mb-3">
        <%= f.label :password, class:"form-label",for:"validationCustom03" %>
        <%= f.password_field :password, class:"form-control form-control-sm",id:"validationCustom03",required:"required" %>
        <div class="invalid-feedback">入力してください</div>
      </div>
      <div class="mb-3">
        <%= f.label :password_confirmation, class:"form-label",for:"validationCustom04" %>
        <%= f.password_field :password_confirmation, class:"form-control form-control-sm",id:"validationCustom04",required:"required" %>
        <div class="invalid-feedback">入力してください</div>
      </div>
      <div class="text-center">
        <%= f.submit "Create account", class:"btn btn-outline-dark btn-sm" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="card card-center" style="max-width:700px;">
    <div class="container-md card-body">
      <div class="row">
        <div class="col-5">
          <div class="card-center" style="width:150px; height:150px;">
            <% if @user.avatar.url %>
             <%= image_tag(@user.avatar.url, class:"avatar-lg") %>
            <% else %>
             <img class="avatar-lg">
            <% end %>
          </div>
        </div>
        <div class="col-7 card-body">
          <div class="">
            <h5><%= @user.name %></h5>
          </div>
          <div class="">
            <p><%= @user.greeting %></p>
          </div>
          <div class="mb-3">
            <%= @user.email %>
          </div>
          <div class="">
            <% if @current_user.id == @user.id %>
              <%= link_to "プロフィールを編集する", edit_user_path(@current_user.id), class:"btn btn-outline-dark btn-sm"  %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <h6><%= @user.name %>さんの投稿写真一覧</h6>
  <div class="card-container">
    <% @pictures.each do |picture| %>
      <%= link_to picture_path(picture.id), class:"card-item" do %>
        <%= image_tag(picture.image.url,class:"square-image") if picture.image && picture.image.url %>
        <div class="card-img-overlay disappear">
          <div class="like-status">
            <table>
              <tbody>
                <tr>
                  <td class="align-middle">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ffffff" class="bi bi-heart-fill" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                    </svg>
                  <%= picture.favorites.count %>
                  </td>
                </tr>
              </tbody>
           </table>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>